/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scramble1981_remastered;

import scramble1981_remastered.view.GameFrame;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        new GameFrame();
    }
}
