/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scramble1981_remastered;

import scramble1981_remastered.model.spaceship.*;
import scramble1981_remastered.view.*;

import javax.swing.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Astronave astronave = new Astronave();

        GameView gv = new GameView();

    }
}
