/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scramble1981_remastered;

import scramble1981_remastered.controller.input.impl.InputControlImpl;
import scramble1981_remastered.view.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        GameView gv = new GameView();
        // final StatesController sc = new StatesController(gv);
        InputControlImpl controller = new InputControlImpl(gv);
        gv.addKeyListener(controller);

    }
}
