/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scramble;

import scramble.view.GameFrame;

/**
 * Class that contein the main method.
 */
public class App {
    /**
     * Greeting.
     * 
     * @return string "Hello World!"
     */
    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * Main method.
     * 
     * @param args
     */
    public static void main(final String[] args) {
        new GameFrame();
    }
}
